#!/bin/sh

#
# Installation script for coordinate loads
#
# 1) cp qtl_coordload.config.default qtl_coordload.config
#    and edit as necessary.
# 2) cp roopenian_sts_coordload.config.default roopenian_sts_coordload
#    and edit as necessary.
# 3) cp tr9601dna_coordload.config.default tr9601dna_coordload.config
#    and edit as necessary.
# 4) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# establish config file names
#
cd `dirname $0`
QTL_CONFIG=qtl_coordload.config
ROOP_STS_CONFIG=roopenian_sts_coordload.config
TR9601DNA_CONFIG=tr9601dna_coordload.config

#
# source qtl and install
#
if [ -r ${QTL_CONFIG} ]
then
    echo "Source ${QTL_CONFIG}"
    . ${QTL_CONFIG}
else
    echo "Cannot source configuration file: ${QTL_CONFIG}"
    installFailed
fi

#
# Check to see if this is a development installation
#
DEV=""

if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall
#
${DLAINSTALL} ${DEV}

#
# source roopenian sts and install
#
if [ -r ${ROOP_STS_CONFIG} ]
then
    echo "Source ${ROOP_STS_CONFIG}"
    . ${ROOP_STS_CONFIG}
else
    echo "Cannot source configuration file: ${ROOP_STS_CONFIG}"
    installFailed
fi

#
# Check to see if this is a development installation
#
DEV=""

if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# source tr9601dna and install
#
if [ -r ${TR9601DNA_CONFIG} ]
then
    echo "Source ${TR9601DNA_CONFIG}"
    . ${TR9601DNA_CONFIG}
else
    echo "Cannot source configuration file: ${TR9601DNA_CONFIG}"
    installFailed
fi

#
# Check to see if this is a development installation
#
DEV=""

if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall
#
${DLAINSTALL} ${DEV}
